version: "3.7"
services:
  mysqldb-test:
    image: mysql:5.7
    container_name: gateway_db_test
    restart: always
    ports:
      - '3310:3306'
    environment:
      MYSQL_DATABASE: ${MYSQL_TEST_DATABASE}
      MYSQL_USER: ${MYSQL_TEST_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_TEST_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_TEST_PASSWORD}
  api-test:
    build:
      context: .
      dockerfile: Dockerfile-test
    container_name: gateway_api_test
    ports:
      - ${SERVER_TEST_PORT}:${SERVER_TEST_PORT}
    env_file:
      - .env
    depends_on:
      - mysqldb-test
