version: "3.7"
services:
  api:
    build: .
    container_name: gateway_api
    restart: always
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    env_file:
      - .env
    networks:
      - springboot-net
  mysqldb:
    image: mysql:5.7
    container_name: gateway_db
    restart: always
    ports:
      - '3309:3306'
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - springboot-net
networks:
  springboot-net:
