version: "3.7"
services:
  mysqldb:
    image: mysql:5.7
    container_name: gateway_db
    restart: always
    ports:
      - '3309:3306'
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
  mysqldb-test:
    image: mysql:5.7
    container_name: gateway_db_test
    restart: always
    ports:
      - '3310:3306'
    environment:
      MYSQL_DATABASE: ${MYSQL_TEST_DATABASE}
      MYSQL_USER: ${MYSQL_TEST_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_TEST_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_TEST_PASSWORD}
