#!/bin/bash
MYSQL_URI="mysql://${MYSQL_TEST_USERNAME}:${MYSQL_TEST_PASSWORD}@${MYSQL_TEST_HOST}:${MYSQL_TEST_PORT}/${MYSQL_TEST_DATABASE}";
/await -t 10m0s $MYSQL_URI -- echo "DATABASE is up!";
mvn test;